name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.7.4
              otp: 21.3.8.17
          - pair:
              elixir: 1.12.0
              otp: 24.0.1

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp-version }} # Define the OTP version [required]
        elixir-version: ${{ matrix.elixir-version }} # Define the elixir version [required]
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
