name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir-version: ['1.8', '1.9', '1.10', '1.11', '1.12']
        otp-version: ['21.0', '22.0', '23.0', '24.0']

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp-version }} # Define the OTP version [required]
        elixir-version: ${{ matrix.elixir-version }} # Define the elixir version [required]
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
